generatorName: typescript-fetch
outputDir: samples/client/petstore/typescript-fetch/builds/utility-types
inputSpec: modules/openapi-generator/src/test/resources/3_1/issue_21317.yaml
templateDir: modules/openapi-generator/src/main/resources/typescript-fetch
